micronaut:
  application:
    name: converterHub
  metrics:
    export:
      stackdriver:
        enabled: true
        projectId: rpa-converter
        step: PT1M
    enabled: true
  server:
    max-request-size: 2GB
    multipart:
      max-file-size: 2GB
      max-request-size: 100MB
      enabled: true
